# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FG.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import PBIcon


class FG_MainWindow(object):
    def setupFG(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 20, 720, 270))
        self.label.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.label.setObjectName("label")
        self.FGPB = QtWidgets.QPushButton(self.centralwidget)
        self.FGPB.setGeometry(QtCore.QRect(30, 310, 50, 50))
        self.FGPB.setStyleSheet("border-image:url(:/STAR.png)")
        self.FGPB.setObjectName("FGPB")
#        self.FGPB_2 = QtWidgets.QPushButton(self.centralwidget)
#        self.FGPB_2.setGeometry(QtCore.QRect(100, 310, 50, 50))
#        self.FGPB_2.setStyleSheet("border-image:url(:/PAUSE.png)")
#        self.FGPB_2.setObjectName("FGPB_2")
        self.FGPB_3 = QtWidgets.QPushButton(self.centralwidget)
        self.FGPB_3.setGeometry(QtCore.QRect(200, 310, 200, 100))
        self.FGPB_3.setObjectName("FGPB_3")
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.FGPB_3.setText("Plot")
