# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.UIPB = QtWidgets.QPushButton(self.centralwidget)
        self.UIPB.setGeometry(QtCore.QRect(50, 50, 230, 80))
        self.UIPB.setStyleSheet("font: 28pt \"Bahnschrift Condensed\";")
        self.UIPB.setObjectName("UIPB")
        self.UIlabel = QtWidgets.QLabel(self.centralwidget)
        self.UIlabel.setGeometry(QtCore.QRect(300, 50, 700, 90))
        self.UIlabel.setStyleSheet("font: 20pt \"Bahnschrift Condensed\";")
        self.UIlabel.setObjectName("UIlabel")
        self.UIPB_2 = QtWidgets.QPushButton(self.centralwidget)
        self.UIPB_2.setGeometry(QtCore.QRect(50, 190, 230, 80))
        self.UIPB_2.setStyleSheet("font: 28pt \"Bahnschrift Condensed\";")
        self.UIPB_2.setObjectName("UIPB_2")
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 25))
        self.menubar.setObjectName("menubar")
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.UIPB.setText(_translate("MainWindow", "Load Data"))
        self.UIlabel.setText(_translate("MainWindow", "file name"))
        self.UIPB_2.setText(_translate("MainWindow", "Continue"))
